enum ProductPricesPermission {
  GET_PRODUCT_PRICES = 'GET_PRODUCT_PRICES',
  CREATE_PRODUCT_PRICE = 'CREATE_PRODUCT_PRICE',
  UPDATE_PRODUCT_PRICE = 'UPDATE_PRODUCT_PRICE',
  EXPORT_PRODUCT_PRICES = 'EXPORT_PRODUCT_PRICES',
  GET_PRODUCT_PRICE = 'GET_PRODUCT_PRICE',
}

export default ProductPricesPermission;
