enum AppointmentsPermission {
  GET_APPOINTMENTS = 'GET_APPOINTMENTS',
  GET_APPOINTMENT = 'GET_APPOINTMENT',
  CREATE_APPOINTMENT = 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT',
}

export default AppointmentsPermission;
