enum SettingsPermission {
  GET_APPOINTMENT_SETTINGS = 'GET_APPOINTMENT_SETTINGS',
  CREATE_APPOINTMENT_SETTING = 'CREATE_APPOINTMENT_SETTING',
  UPDATE_APPOINTMENT_SETTING = 'UPDATE_APPOINTMENT_SETTING',
}

export default SettingsPermission;
